version: "3"
services:
    fastemail:
      image: fonzeca/fastemail:dev
      volumes:
        - ${PWD}/.env:/app/.env
      networks:
        - carmind

networks:
  carmind:
    driver: bridge
    name: carmind
    external: true