version: "3"
services:
    fastemail:
      image: fonzeca/fastemail:dev
      env_file:
      - .env
      networks:
        - carmind

networks:
  carmind:
    driver: bridge
    name: carmind
    external: true